# CodeSandbox supports debian & ubuntu based images
FROM alpine

# Example; install htop by default
RUN apk update && apk upgrade

# The project will be mounted in /workspace by default

# Every new shell will open inside the built container

# On top of this build, we install `zsh`, `git` and `docker` as additional
# Docker layers.
